// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHpL8MLTNNP_OozYeag2Hy-kBbh89tjeU',
    appId: '1:947087409633:web:c36d2d59d5dc54c70e52a0',
    messagingSenderId: '947087409633',
    projectId: 'fitgenius-58ca2',
    authDomain: 'fitgenius-58ca2.firebaseapp.com',
    storageBucket: 'fitgenius-58ca2.appspot.com',
    measurementId: 'G-EE5NW247R3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWo8Hk2hx6ije9sSR8JGtteoNlvpmBRrc',
    appId: '1:947087409633:android:a4f4fce4028b39820e52a0',
    messagingSenderId: '947087409633',
    projectId: 'fitgenius-58ca2',
    storageBucket: 'fitgenius-58ca2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiVjNGK1MerEDRml-wr8w8kqlQ1wGr2H0',
    appId: '1:947087409633:ios:3233b349fb3a7cfe0e52a0',
    messagingSenderId: '947087409633',
    projectId: 'fitgenius-58ca2',
    storageBucket: 'fitgenius-58ca2.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiVjNGK1MerEDRml-wr8w8kqlQ1wGr2H0',
    appId: '1:947087409633:ios:3233b349fb3a7cfe0e52a0',
    messagingSenderId: '947087409633',
    projectId: 'fitgenius-58ca2',
    storageBucket: 'fitgenius-58ca2.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHpL8MLTNNP_OozYeag2Hy-kBbh89tjeU',
    appId: '1:947087409633:web:b0a6b32a062c41bc0e52a0',
    messagingSenderId: '947087409633',
    projectId: 'fitgenius-58ca2',
    authDomain: 'fitgenius-58ca2.firebaseapp.com',
    storageBucket: 'fitgenius-58ca2.appspot.com',
    measurementId: 'G-2QX29E7VPD',
  );
}
